version: '3.8'

services:
  # Django Application
  web:
    build: .
    container_name: padlevb-django
    command: daphne -b 0.0.0.0 -p 8000 padlevb.asgi:application
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=padlevb.settings.production
      - DATABASE_URL=postgresql://useralbert:Goamico&DB@db:5432/goamicodatabase
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env.production
    depends_on:
      - db
      - redis
    restart: unless-stopped
    networks:
      - app-network

  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: padlevb-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=goamicodatabase
      - POSTGRES_USER=useralbert
      - POSTGRES_PASSWORD=Goamico&DB
    restart: unless-stopped
    networks:
      - app-network

  # Redis for Channels and caching
  redis:
    image: redis:7-alpine
    container_name: padlevb-redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - app-network

  # Nginx (optional - for production)
  nginx:
    image: nginx:alpine
    container_name: padlevb-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./ssl:/etc/ssl/certs
    depends_on:
      - web
    restart: unless-stopped
    networks:
      - app-network

  # Celery (optional - for background tasks)
  celery:
    build: .
    container_name: padlevb-celery
    command: celery -A padlevb worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=padlevb.settings.production
      - DATABASE_URL=postgresql://padlevb:password@db:5432/padlevb
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env.production
    depends_on:
      - db
      - redis
    restart: unless-stopped
    networks:
      - app-network

  # Celery Beat (optional - for scheduled tasks)
  celery_beat:
    build: .
    container_name: padlevb-celery-beat
    command: celery -A padlevb beat --loglevel=info
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=padlevb.settings.production
      - DATABASE_URL=postgresql://padlevb:password@db:5432/padlevb
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env.production
    depends_on:
      - db
      - redis
    restart: unless-stopped
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:

networks:
  app-network:
    driver: bridge