"""
Django settings for padlevb project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from datetime import timedelta
from pathlib import Path

import cloudinary
import cloudinary.uploader
import cloudinary.api
from dotenv import load_dotenv
from urllib.parse import urlparse
import pytesseract

# Load environment variables from .env file
load_dotenv()
# Parse the DATABASE_URL environment variable
#tmpPostgres = urlparse(os.getenv("DATABASE_URL"))
#key = urlparse(os.getenv("SECRET_KEY"))
#emailUser = urlparse(os.getenv("EMAIL_HOST_USER"))
#emailPassword = urlparse(os.getenv("EMAIL_HOST_PASSWORD"))
# Build paths inside the project like this: BASE_DIR / 'subdir'.

BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/
SECRET_KEY = os.getenv('SECRET_KEY')

# Debug mode (set to False in production)
DEBUG = False

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = 'django-insecure-!0@_8@i^*k8%0j$t#z)4j-(38o&u&+$n_$cw(!i&la)8-w&@5&'


ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'padlevap',
    'rest_framework',
    'corsheaders',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'djoser',
    'cloudinary',
    'django_celery_beat',
    'django_filters',
    'social_django',
    'channels',
]

MIDDLEWARE = [
 
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add this line
]

ROOT_URLCONF = 'padlevb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'padlevb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
        'OPTIONS': {
            'sslmode': 'require',  # Enforce SSL
        },
    }
}
#print(f"DB KEY: {os.getenv('SECRET_KEY')}")
#print(f"DB NAME: {os.getenv('DB_NAME')}")
#print(f"DB USER: {os.getenv('DB_USER')}")
#print(f"DB HOST: {os.getenv('DB_HOST')}")

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'padlevb/staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'padlevap.UserAccount'


REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    #'DEFAULT_PERMISSION_CLASSES': [
     #   'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    #]
     'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend', 'rest_framework.filters.SearchFilter'],
        'DEFAULT_AUTHENTICATION_CLASSES': [
      #  'rest_framework.authentication.SessionAuthentication',  # Session-based auth
        #'rest_framework.authentication.TokenAuthentication',    # Token-based auth
         'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],

}


CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('redis', 6379)],
        },
    },
}
#127.0.0.1

SIMPLE_JWT = {
    'AUTH_HEADER_TYPES': ('JWT',),
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'AUTH_TOKEN_CLASSES': (
        'rest_framework_simplejwt.tokens.AccessToken',
    )
}

# Zoho Mail SMTP Configuration
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND')
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = os.getenv('EMAIL_PORT')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')



AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.facebook.FacebookOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)




DJOSER = {
    'LOGIN_FIELD': 'email',
    'USER_CREATE_PASSWORD_RETYPE': False,
    'USERNAME_CHANGED_EMAIL_CONFIRMATION': True,
    'PASSWORD_CHANGED_EMAIL_CONFIRMATION': True,
    #'SEND_CONFIRMATION_EMAIL': True,
    #'SET_USERNAME_RETYPE': True,
    #'SET_PASSWORD_RETYPE': True,
    'PASSWORD_RESET_CONFIRM_URL': 'reset-password/{uid}/{token}',
    'USERNAME_RESET_CONFIRM_URL': 'reset-email/{uid}/{token}',
    'EMAIL': {
        'password_reset': 'padlevap.user_email.PasswordResetEmail',
        'username_reset': 'padlevap.user_email.UsernameResetEmail',
        'password_changed_confirmation': 'padlevap.user_email.PasswordChangedConfirmation',
        'username_changed_confirmation': 'padlevap.user_email.UsernameChangedConfirmation',
    },
    #'ACTIVATION_URL': 'activate/{uid}/{token}',
    #'SEND_ACTIVATION_EMAIL': True,
    'SOCIAL_AUTH_TOKEN_STRATEGY': 'djoser.social.token.jwt.TokenStrategy',
    'SOCIAL_AUTH_ALLOWED_REDIRECT_URIS': [
        # Local development (NextAuth)
        'http://localhost:3000/api/auth/callback/google',
        'http://localhost:3000/api/auth/callback/facebook',

        # Production (NextAuth)
        'https://goamico.com/api/auth/callback/google',
        'https://goamico.com/api/auth/callback/facebook',
        'https://www.goamico.com/api/auth/callback/google',
        'https://www.goamico.com/api/auth/callback/facebook',

        # API subdomain
        'https://api.goamico.com/api/auth/callback/google',
        'https://api.goamico.com/api/auth/callback/facebook',

        # Django OAuth endpoints (direct login)
        'http://localhost:3000/auth/o/google-oauth2/',
        'http://localhost:3000/auth/o/facebook/',
        'https://api.goamico.com/auth/o/google-oauth2/',
        'https://api.goamico.com/auth/o/facebook/',
    ],
    'SERIALIZERS': {
        'user_create': 'padlevap.serializers.UserCreateSerializer',
        'user': 'padlevap.serializers.InformationsSerializer',
        'current_user': 'padlevap.serializers.InformationsSerializer',
        'user_delete': 'djoser.serializers.UserDeleteSerializer',
        
    }
}

# Social Auth Settings
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.getenv('SOCIAL_AUTH_GOOGLE_OAUTH2_KEY')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.getenv('SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET')
SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = ['email', 'profile', 'openid']


# Add these additional Google OAuth2 settings
SOCIAL_AUTH_GOOGLE_OAUTH2_EXTRA_DATA = ['first_name', 'last_name', 'picture']
SOCIAL_AUTH_GOOGLE_OAUTH2_USE_DEPRECATED_API = False



# Social Auth Settings - Facebook
SOCIAL_AUTH_FACEBOOK_KEY = os.getenv('SOCIAL_AUTH_FACEBOOK_KEY')
SOCIAL_AUTH_FACEBOOK_SECRET = os.getenv('SOCIAL_AUTH_FACEBOOK_SECRET')
SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']
SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {
    'fields': 'id,name,email,first_name,last_name,picture'
}


#CORS_ALLOWED_ORIGINS = [
#    "http://localhost:3000",  # Replace with your frontend URL
#    "https://www.padlev.com",  # Add other trusted origins    
#   "https://padlev.vercel.app",
#   "https://trustdine-xi.vercel.app",  
#]
CORS_ORIGIN_ALLOW_ALL = True
# Allow credentials (optional, only enable if needed)
CORS_ALLOW_CREDENTIALS = True

cloudinary.config( 
  cloud_name = os.getenv('CLOUDINARY_CLOUD_NAME'),
  api_key = os.getenv('CLOUDINARY_API_KEY'),
  api_secret = os.getenv('CLOUDINARY_API_SECRET'),

)
import ssl  # <-- Add this import at the top of the file
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL'),
CELERY_RESULT_BACKEND = os.getenv('CELERY_BROKER_URL'),
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_ENABLE_UTC = True
# SSL Configuration
CELERY_REDIS_BACKEND_USE_SSL = {
    'ssl_cert_reqs': ssl.CERT_NONE
}
CELERY_BROKER_USE_SSL = {
    'ssl_cert_reqs': ssl.CERT_NONE
}
# Add this line to suppress the warning
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True


pytesseract.pytesseract.tesseract_cmd = "/usr/bin/tesseract"

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

CSRF_TRUSTED_ORIGINS = [
    'https://api.goamico.com',
    'https://goamico.com',
    'https://www.goamico.com',
]

# Also ensure CSRF protection is properly configured
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
# Ensure Django knows it's behind HTTPS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True




# Phone OTP Configuration
PHONE_OTP_EXPIRE_TIME = 300  # 5 minutes
PHONE_OTP_MAX_ATTEMPTS = 3
PHONE_OTP_LENGTH = 6

# SMS Configuration (Twilio)
TWILIO_ACCOUNT_SID = os.getenv('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN = os.getenv('TWILIO_AUTH_TOKEN', '')
TWILIO_PHONE_NUMBER = os.getenv('TWILIO_PHONE_NUMBER', '')

