# Generated by Django 5.1.6 on 2025-04-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padlevap', '0002_scheduledemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledemail',
            name='language',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
