# Generated by Django 5.1.6 on 2025-04-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padlevap', '0003_scheduledemail_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledemail',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
