# Generated by Django 5.1.6 on 2025-05-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padlevap', '0005_alter_post_image_ar_alter_post_image_de_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_de',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_it',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_nl',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_pt',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_sv',
        ),
        migrations.AddField(
            model_name='product',
            name='content_ar',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='content_de',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='content_en',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='content_es',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='content_fr',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='content_it',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='content_nl',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='content_pt',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='content_ru',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='content_sv',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
