# Generated by Django 5.1.6 on 2025-06-19 18:02

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padlevap', '0007_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='image_url',
        ),
        migrations.AddField(
            model_name='test',
            name='image_en',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
