# Generated by Django 5.1.6 on 2025-07-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padlevap', '0009_useraccount_is_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='partner',
            field=models.BooleanField(default=False),
        ),
    ]
