# Generated by Django 5.1.6 on 2025-07-07 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padlevap', '0011_remove_useraccount_is_partner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='partner',
            new_name='is_partner',
        ),
    ]
