# Generated by Django 5.1.6 on 2025-07-07 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padlevap', '0012_rename_partner_useraccount_is_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='is_partner',
        ),
    ]
