# Generated by Django 5.1.6 on 2025-07-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padlevap', '0014_useraccount_about_useraccount_born_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='joined',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
