# Generated by Django 5.1.6 on 2025-07-31 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padlevap', '0017_remove_sizevariation_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreview',
            old_name='color',
            new_name='stay_date',
        ),
        migrations.RenameField(
            model_name='productreview',
            old_name='country',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='productreview',
            old_name='size',
            new_name='trip_type',
        ),
        migrations.AddField(
            model_name='emailletter',
            name='company',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='emailletter',
            name='first_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='emailletter',
            name='last_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='emailletter',
            name='message',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='types',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
