# Generated by Django 5.1.6 on 2025-08-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padlevap', '0018_rename_color_productreview_stay_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenities',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
