# Generated by Django 5.1.6 on 2025-08-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padlevap', '0019_amenities_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenities',
            name='categoty',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
