# Generated by Django 5.1.6 on 2025-08-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padlevap', '0020_amenities_categoty'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='language',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
