# Generated by Django 5.1.6 on 2025-08-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padlevap', '0021_useraccount_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='awards',
            old_name='awards',
            new_name='name',
        ),
        migrations.AddField(
            model_name='awards',
            name='year',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
