# Generated by Django 5.1.6 on 2025-08-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padlevap', '0022_rename_awards_awards_name_awards_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='zero_waste_initiatives',
            new_name='latitude',
        ),
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='longtitude',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='organic_ingredients',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='sustainable_seafood',
            field=models.BooleanField(default=False),
        ),
    ]
