# Generated by Django 5.1.6 on 2025-08-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padlevap', '0024_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='longtitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
