# Generated by Django 5.1.6 on 2025-08-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padlevap', '0027_reviewscore_reviewhelpful_reviewreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewreport',
            name='informations',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
