# Generated by Django 5.1.6 on 2025-08-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padlevap', '0028_reviewreport_informations'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rooms_number',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
