# Generated by Django 5.1.6 on 2025-08-23 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padlevap', '0029_product_rooms_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rooms_number',
        ),
    ]
