# Generated by Django 5.1.6 on 2025-08-23 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padlevap', '0032_order_cancellation_policy_order_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cancellation_policy',
        ),
        migrations.RemoveField(
            model_name='order',
            name='category',
        ),
        migrations.RemoveField(
            model_name='order',
            name='location',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
    ]
