# Generated by Django 5.1.6 on 2025-08-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padlevap', '0033_remove_order_cancellation_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
