# Generated by Django 5.1.6 on 2025-08-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padlevap', '0035_order_cancellation_policy_order_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_owner',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
