# Generated by Django 5.1.6 on 2025-08-27 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padlevap', '0037_chatroom_message_onlineuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewscore',
            name='review',
        ),
        migrations.AddField(
            model_name='reviewscore',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='score', to='padlevap.product'),
            preserve_default=False,
        ),
    ]
