# Generated by Django 5.1.6 on 2025-08-30 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padlevap', '0038_remove_reviewscore_review_reviewscore_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlineuser',
            name='room',
        ),
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),

        migrations.RemoveField(
            model_name='onlineuser',
            name='user',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='is_deleted',
            new_name='is_read',
        ),
        migrations.RemoveField(
            model_name='message',
            name='edited_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_edited',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_type',
        ),
        migrations.RemoveField(
            model_name='message',
            name='parent_message',
        ),
        migrations.RemoveField(
            model_name='message',
            name='read_by',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.DeleteModel(
            name='OnlineUser',
        ),
    ]
