# Generated by Django 5.1.6 on 2025-08-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padlevap', '0039_remove_onlineuser_room_remove_message_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='te',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
