# Generated by Django 5.1.6 on 2025-08-30 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padlevap', '0040_message_te'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='te',
        ),
    ]
