# Generated by Django 5.1.6 on 2025-08-31 11:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padlevap', '0041_remove_message_te'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='receipt',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='images'),
        ),
    ]
