# Generated by Django 5.1.6 on 2025-09-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padlevap', '0042_product_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receipt',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
