# Generated by Django 5.1.6 on 2025-09-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padlevap', '0043_order_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_inwishlist',
            field=models.BooleanField(default=False),
        ),
    ]
