# Generated by Django 5.1.6 on 2025-09-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padlevap', '0044_product_is_inwishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailletter',
            name='category',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='emailletter',
            name='full_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='emailletter',
            name='subject',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
