# Generated by Django 5.1.6 on 2025-09-19 08:13

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padlevap', '0046_remove_product_is_inwishlist_emailletter_is_read_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('document_type', models.CharField(blank=True, max_length=500, null=True)),
                ('document_number', models.CharField(blank=True, max_length=500, null=True)),
                ('document_photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='images')),
                ('selfie_document', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='images')),
                ('date', models.CharField(blank=True, max_length=500, null=True)),
                ('time', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='useraccount',
            name='premium_plan',
            field=models.BooleanField(default=False),
        ),
    ]
