# Generated by Django 5.1.6 on 2025-09-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padlevap', '0047_verify_useraccount_premium_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='verify',
            name='status',
            field=models.CharField(blank=True, default='unverified', max_length=500, null=True),
        ),
    ]
