# Generated by Django 5.1.6 on 2025-09-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padlevap', '0048_verify_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
