# Generated by Django 5.1.6 on 2025-09-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padlevap', '0049_alter_useraccount_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
