# Generated by Django 5.1.6 on 2025-09-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padlevap', '0050_useraccount_is_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='hotel_stars',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
