# Generated by Django 5.1.6 on 2025-09-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padlevap', '0052_verify_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=15)),
                ('otp_code', models.CharField(max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number', 'is_verified'], name='padlevap_ph_phone_n_c6ea86_idx')],
            },
        ),
    ]
