# Generated by Django 5.1.6 on 2025-09-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padlevap', '0053_phoneotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_phone_number_verified',
            field=models.BooleanField(default=False),
        ),
    ]
