# Generated by Django 5.1.6 on 2025-09-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padlevap', '0054_useraccount_is_phone_number_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailletter',
            name='message_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
